service: sensitive-data-security-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  detectPii:
    handler: src/controller/detectPii/handler.detectPii
    events:
      - http:
          path: detectPii
          method: post


plugins:
  - serverless-esbuild
  - serverless-offline
