service: sensitive-data-security-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get


plugins:
  - serverless-esbuild
  - serverless-offline
