service: sensitive-data-security-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "comprehend:DetectPiiEntities"
          Resource:
            - "*"


functions:
  detectPii:
    handler: src/controller/detectPii/handler.detectPii
    events:
      - http:
          path: detectPii
          method: post


plugins:
  - serverless-esbuild
  - serverless-offline
